name: Final Build Example

on:
  workflow_dispatch:

jobs:
  build-example:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Node.js / NPM
      - name: Set up Node.js / NPM
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install project dependencies
      - name: Install NPM dependencies
        run: npm install

      # 4. Run unit tests + generate report
      - name: Run unit tests
        run: |
          # Install junit reporter if not included in package.json
          npm install --save-dev jest-junit
          
          # Run tests with junit output
          npx jest --ci --reporters=default --reporters=jest-junit

      # 5. Upload test report as artifact
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: jest-reports.xml

      # 6 Better test report
      - name: Better test report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results

      # 6. Bundle application into ZIP (app files + node_modules)
      - name: Bundle application into ZIP
        run: |
          zip -r app_bundle.zip . \
            -x "*.git*" \
               ".*" \
               "*node_modules/.cache*"
