name: Final Build Example

on:
  workflow_dispatch:

jobs:
  build-example:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Node.js / NPM
      - name: Set up Node.js / NPM
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install project dependencies
      - name: Install NPM dependencies
        run: npm install

      # Run unit tests + generate report
      - name: Run unit tests
        env:
          JEST_JUNIT_OUTPUT: reports/jest-results.xml
        run: |
          mkdir -p reports
          npm install --save-dev jest-junit
          npx jest --ci --reporters=default --reporters=jest-junit
      
      # Upload test report
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/jest-results.xml
      
      # Better test report
      - name: Better test report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: JEST Tests
          path: reports/jest-results.xml
          reporter: jest-junit

      # 6. Bundle application into ZIP (app files + node_modules)
      - name: Bundle application into ZIP
        run: |
          zip -r app_bundle.zip . \
            -x "*.git*" \
               ".*" \
               "*node_modules/.cache*"
